# Generated by Django 3.0.3 on 2020-02-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
